language: node_js
node_js:
- 4.4.7
branches:
  only:
  - Hexo_Source
before_install:
- npm install -g hexo-cli
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- git config --global user.name "Blackie Tsai"
- git config --global user.email "blackie1019@gmail.com"
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
- hexo deploy
env:
  global:
    secure: iDaLIwkbGAobUyWbYtf9oVNJzeusvYkPy4r8Kjojdik6YkxprCbHEj6Gzc5nstUM3nkOk/y5l2NaXxF44iyxgS/mqdcp/SfrkJzrczs+MBLHNVscTpHQajaN4DZj9UWPokMipqJD7+QFBBScf9v2WqXQCi0osZM6esS6P2st/G7qHbD+Y0T5NGvzGrlTa0JBA0WN1MyuKx53v+0S83GKRmpqk10gfEooI7sO01EhaxHe/aDTyx+dHzI/eaKpYuWZt+xPcl/yPlq+HE4Sn9JHIUmISDIJ6WtLXvj+XGiExWM9QCvVfnMLrsqTVgzrr3eoltboFibgqUuy37bwTya5rJpHLiwjfa/aIOjORt6LNzDuK6no0Yrl+PHF2G2vpWjo2ZwNxGKopcQppRlqegtP+oNx/GJ+u2JH/8mswMLn9OsxVMt9hBAZiU+PW1iNdj9MRJnUJdciPH+anmEYmt81eyres9FjDi6laXyQj7V7RALnfry0zXA42gVcYfsC8qCfyULOfFLUG7gOVVbqMzZpY9Jy8Ye2yh+qmSRPFj3PABCwMTzYHneoKcPha0ZnWAn98HmRJRSgK3C0pneglsjv2Vs1F2sgcTdGt33ntGsO9AreQVpCOxQ14pENyVVP1MA+Hiwref6JnqIXwGdwg+ym6VPGa1ZOIaSYXaOAATW92w0=
