language: node_js
node_js:
- '0.12'
branches:
  only:
  - hexo
before_install:
- npm install -g hexo-cli
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- git config --global user.name "Blackie Tsai"
- git config --global user.email "blackie1019@gmail.com"
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
- hexo deploy
env:
  global:
    secure: LQD7RChdoD02jaxRnt62/QpKPsTJzoyEggHaOoVMQkpqFOTQKkxP+E8EjOh9RV+LO5IzW4NaCtPpShMwj9Fbm88bhLKB5+2nnUf/trgVbtOgQseIXhh4/V4Aau0uqvMSRx294JZbp9A/LBm/M7JeZvR/yHnikw5JairOGs9wAt/3U9Wdz21DWWg1roWJtWK28ftVKSy7zfTaE8DiOCEFkgGBuV/JYdPBbJSrSmismlqH8EUv6PIfI2HDz+iyGTmkBXVTJYbslBuYwC5XnhVx2cUMG4JdiyljxTFl0BIE7su64i/MJA3O+ldl6n6Plb3VzlAG/k8pgn3NHBS2u5slSKuR3D4SHVS1mTJOI31RtAB72JLRdW/LHDX8VfZ9VTOCYKAaBqbxhC+rBs/oOa7SmHqJZcvr4MUZIObMggfBSxHGB4auAgM0ptJWHCu7iPEvxpE7WCKf28HQmT/b+ZXA/6IgGCuyBBZsVXqbf4YkGterYdQRg4GB5z9J1FQJUOovckW+rn5qUxROQsD9C+DQ58JwksM3fJDMSjyKDD+Nm+qNWFl9Ci70Ic0oFS3hp7XIYOjwkCZ6Rap/5bONeY8LvE58FQklIGO2ZAqUbT0m4tchCI/tpo8Hzr3zhbV/6qdNhqYaGcTId70k5YWovtTp4gMukrzDnY/Rbdqjx5n9RY4=
