# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Blackie's Failed Notes
subtitle : Show me. Don't tell me.
description: Interested in JavaScript, ASP.NET Core, Cloud and Solution Architecture.
quote: Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better. 
author: Blackie Tsai
avatar: img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`
language: en
timezone: Asia/Taipei

# Search
search:
  path: search.xml
  field: post

# Sitemap
sitemap:
  path: sitemap.xml
  template: ./sitemap_template.xml

# RSS
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blackie1019.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: false
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page
index_generator:
  per_page: 20
archive_generator:
  per_page: 100
  yearly: true
  monthly: true
tag_generator:
  per_page: 50
  
# Extensions
## Themes: https://hexo.io/themes/
theme: next

## Plugins: https://hexo.io/plugins/

# https://github.com/leecrossley/hexo-generator-robotstxt
robotstxt:
  useragent: "*"
  disallow:
    - /css/
    - /images/
    - /img/
    - /js/
    - /fonts/
    - /vendors/
    - /fancybox/
  allow:
    - /
    - /archives/
    - /categories/
    - /tags/
  sitemap: https://blackie1019.github.io/sitemap.xml
  
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/blackie1019/blackie1019.github.io.git
  branch: master

# Livereload
livereload:
  port: 40001

# Hexo-filter-cleanup https://github.com/mamboer/hexo-filter-cleanup
hfc_useref:
  enable: true
  concat: true
  exclude: 

hfc_html:
  enable: true
  exclude: 

hfc_css:
  enable: true
  exclude: 
    - '*.min.css'

hfc_js:
  enable: false
  mangle: true
  output:
  compress:
  exclude: 
    - '*.min.js'

hfc_img:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  webp: true
  webpQuality: 75
  gifslice: true
  jpegtran: true
  jpegrecompress: false
  jpegrecompressQuality: 'medium'
  optipng: true
  svgo: true

hfc_favicons:
  enable: false
  src: 
  target: img/
  icons:
    android: true
    appleIcon: true
    appleStartup: false
    coast: false
    favicons: true
    firefox: false
    opengraph: false
    windows: true
    yandex: false